"""Configuration loading for the Telegram bot."""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional

from dotenv import load_dotenv
import logging


DEFAULT_DO_API_BASE_URL = "https://api.digitalocean.com/v2/gen-ai"


@dataclass(slots=True)
class BotConfig:
    """Runtime configuration for the Telegram bot.

    Attributes
    ----------
    telegram_bot_token:
        Token generated by BotFather for the Telegram bot.
    do_api_key:
        Personal access token for the DigitalOcean AI Agent API.
    do_agent_id:
        Identifier of the AI Agent instance to forward messages to.
    do_api_base_url:
        Optional override for the DigitalOcean API base URL.
    request_timeout:
        Timeout (seconds) for outbound HTTP requests.
    """

    telegram_bot_token: str
    do_api_key: str
    do_agent_id: str
    do_api_base_url: str = DEFAULT_DO_API_BASE_URL
    request_timeout: float = 30.0
    # Optional agent endpoint + access key for direct endpoint usage
    agent_endpoint: Optional[str] = None
    agent_access_key: Optional[str] = None
    # Retry/backoff configuration for DigitalOcean API requests
    api_max_retries: int = 3
    api_base_backoff: float = 0.5
    api_max_backoff: float = 60.0
    # Token-bucket rate limiter for outgoing requests to DigitalOcean
    api_rate_limit_qps: float = 5.0
    api_rate_limit_burst: int = 10
    api_rate_limit_cooldown: float = 5.0

    @classmethod
    def load(cls, env_path: Optional[str] = None) -> "BotConfig":
        """Load configuration from the process environment.

        Parameters
        ----------
        env_path:
            Optional path to a ``.env`` file. If provided, variables in the file
            will be loaded before reading from the environment.

        Returns
        -------
        BotConfig
            The populated configuration.

        Raises
        ------
        RuntimeError
            If any required configuration values are missing.
        """

        if env_path:
            load_dotenv(env_path)
        else:
            # Load from default .env if it exists.
            load_dotenv()

        token = os.getenv("TELEGRAM_BOT_TOKEN")
        api_key = os.getenv("DO_API_KEY")
        agent_id = os.getenv("DO_AGENT_ID")
        base_url = os.getenv("DO_API_BASE_URL") or DEFAULT_DO_API_BASE_URL
        agent_endpoint = os.getenv("AGENT_ENDPOINT")
        agent_access_key = os.getenv("AGENT_ACCESS_KEY")
        timeout_str = os.getenv("DO_API_TIMEOUT", "30")

        if not token:
            raise RuntimeError("TELEGRAM_BOT_TOKEN is not configured")
        if not api_key:
            raise RuntimeError("DO_API_KEY is not configured")
        if not agent_id:
            raise RuntimeError("DO_AGENT_ID is not configured")

        # Normalize common legacy base URL value and warn the operator. Some
        # deployments (older docs/examples) used `/v2/ai`; the correct current
        # base path is `/v2/gen-ai`. Normalize transparently so existing installs
        # don't fail with 404s.
        if base_url and base_url.rstrip("/").endswith("/v2/ai"):
            logging.getLogger(__name__).warning(
                "DO_API_BASE_URL uses legacy '/v2/ai' path; normalizing to '/v2/gen-ai'"
            )
            base_url = base_url.rstrip("/").replace("/v2/ai", "/v2/gen-ai")

        try:
            timeout = float(timeout_str)
        except ValueError as exc:
            raise RuntimeError("DO_API_TIMEOUT must be numeric") from exc

        return cls(
            telegram_bot_token=token,
            do_api_key=api_key,
            do_agent_id=agent_id,
            do_api_base_url=base_url,
            request_timeout=timeout,
            agent_endpoint=agent_endpoint,
            agent_access_key=agent_access_key,
            api_max_retries=int(os.getenv("DO_API_MAX_RETRIES", "3")),
            api_base_backoff=float(os.getenv("DO_API_BASE_BACKOFF", "0.5")),
            api_max_backoff=float(os.getenv("DO_API_MAX_BACKOFF", "60")),
            api_rate_limit_qps=float(os.getenv("DO_API_RATE_QPS", "5")),
            api_rate_limit_burst=int(os.getenv("DO_API_RATE_BURST", "10")),
            api_rate_limit_cooldown=float(os.getenv("DO_API_RATE_COOLDOWN", "5")),
        )
